---
- hosts: webserver
  become: yes
  gather_facts: yes
  tasks:
  - name: I wanna install openjdk8 on ubuntu nodes
    apt:
      name: "{{javaonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"
  
  - name: I wanna install openjdk8 on Redhat nodes
    yum:
      name: "{{javaonRedHat}}"
      state: present
    when: ansible_os_family =="RedHat"