---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: I wanna install webserver on Ubuntu nodes
    apt:
      name: "{{webpackforubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: I wanna start service on Ubuntu nodes
    service:
      name: "{{webpackforubuntu}}"
      state: started
    when: ansible_os_family =="Debian"

  - name: I wanna install webserver on Redhat nodes
    yum:
     name: "{{webpackforRedHat}}"
     state: present
    when: ansible_os_family =="RedHat"

  - name: I wanna start service on Redhat nodes
    service:
     name: "{{webpackforRedHat}}"
     state: started
    when: ansible_os_family =="RedHat"