---
- name: Give the tomcat group ownership /opt/tomcat directory
  file:
     path: /opt/tomcat
     recurse: yes
     group: tomcat
     state: directory

- name: give the tomcat group read access to the conf directory
  file:
     path: /opt/tomcat/conf
     recurse: yes
     mode: g+r       # Group level read access i'm giving
     state: directory

- name: give the tomcat group execute access to the conf directory
  file:
     path: /opt/tomcat/conf
     mode: g+x      # Here no Recurse mode so that way we did give the permissions
     state: directory

- name: Make the tomcat user the owner of the webapps
  file:
     path: /opt/tomcat/webapps/
     recurse: yes
     owner: tomcat
     state: directory            # Same thing repeat 3- times

- name: Make the tomcat user the owner of the Work directory
  file:
     path: /opt/tomcat/work/
     recurse: yes
     owner: tomcat
     state: directory

- name: Make the tomcat user the owner of the temp directory
  file:
     path: /opt/tomcat/temp/
     recurse: yes
     owner: tomcat
     state: directory

- name: Make the tomcat user the owner of the logs directory
  file:
     path: /opt/tomcat/logs/
     recurse: yes
     owner: tomcat
     state: directory